#!/data/data/com.termux/files/usr/bin/bash
set -e

RES="app/src/main/res"
JAVA_FILE="app/src/main/java/com/android/gallery3d/app/GalleryActivity.java"
MAIN_LAYOUT="app/src/main/res/layout/main.xml"
STRINGS="app/src/main/res/values/strings.xml"

echo "== Criando drawables da barra inferior =="
cat > "$RES/drawable/bottom_nav_pill_background.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
        android:shape="rectangle">
    <solid android:color="#2A2A2E" />
    <corners android:radius="32dp" />
</shape>
EOF

cat > "$RES/drawable/bottom_nav_selected_pill.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<shape xmlns:android="http://schemas.android.com/apk/res/android"
        android:shape="rectangle">
    <solid android:color="#4285f4" />
    <corners android:radius="24dp" />
</shape>
EOF

cat > "$RES/drawable/ic_nav_gallery3d.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24"
        android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M4,4h10v10H4V4zM6,6v6h6V6H6zM14,4h6v6h-6V4zM16,6v2h2V6h-2zM4,16h6v4H4v-4zM6,18v0h2v0H6zM14,14h6v10h-6V14zM16,16v6h2v-6h-2z"/>
</vector>
EOF

cat > "$RES/drawable/ic_nav_music3d.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<vector xmlns:android="http://schemas.android.com/apk/res/android"
        android:width="24dp"
        android:height="24dp"
        android:viewportWidth="24"
        android:viewportHeight="24">
    <path
        android:fillColor="#FFFFFFFF"
        android:pathData="M12,3v10.55c-0.59,-0.34 -1.27,-0.55 -2,-0.55 -2.21,0 -4,1.79 -4,4s1.79,4 4,4 4,-1.79 4,-4V7h4V3h-6z"/>
</vector>
EOF

echo "== Criando layout da barra inferior =="
cat > "$RES/layout/bottom_nav_bar.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/bottom_nav_bar"
        android:layout_width="wrap_content"
        android:layout_height="64dp"
        android:layout_alignParentBottom="true"
        android:layout_centerHorizontal="true"
        android:layout_marginBottom="24dp"
        android:orientation="horizontal"
        android:background="@drawable/bottom_nav_pill_background"
        android:elevation="12dp"
        android:paddingLeft="8dp"
        android:paddingRight="8dp"
        android:paddingTop="8dp"
        android:paddingBottom="8dp">

    <LinearLayout
            android:id="@+id/nav_tab_gallery3d"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:orientation="horizontal"
            android:gravity="center"
            android:clickable="true"
            android:focusable="true"
            android:background="@drawable/bottom_nav_selected_pill"
            android:paddingLeft="20dp"
            android:paddingRight="20dp">

        <ImageView
                android:layout_width="22dp"
                android:layout_height="22dp"
                android:src="@drawable/ic_nav_gallery3d"
                android:contentDescription="@string/nav_tab_gallery3d" />

        <TextView
                android:id="@+id/nav_tab_gallery3d_label"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="8dp"
                android:text="@string/nav_tab_gallery3d"
                android:textColor="#FFFFFF"
                android:textSize="14sp"
                android:textStyle="bold" />
    </LinearLayout>

    <View
            android:layout_width="8dp"
            android:layout_height="1dp" />

    <LinearLayout
            android:id="@+id/nav_tab_music3d"
            android:layout_width="wrap_content"
            android:layout_height="match_parent"
            android:orientation="horizontal"
            android:gravity="center"
            android:clickable="true"
            android:focusable="true"
            android:background="@android:color/transparent"
            android:paddingLeft="20dp"
            android:paddingRight="20dp">

        <ImageView
                android:layout_width="22dp"
                android:layout_height="22dp"
                android:src="@drawable/ic_nav_music3d"
                android:contentDescription="@string/nav_tab_music3d" />

        <TextView
                android:id="@+id/nav_tab_music3d_label"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginLeft="8dp"
                android:text="@string/nav_tab_music3d"
                android:textColor="#A9ABAD"
                android:textSize="14sp"
                android:textStyle="bold" />
    </LinearLayout>

</LinearLayout>
EOF

cat > "$RES/layout/music3d_placeholder.xml" << 'EOF'
<?xml version="1.0" encoding="utf-8"?>
<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:id="@+id/music3d_placeholder_root"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:background="#1A1A1A"
        android:visibility="gone">

    <LinearLayout
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_gravity="center"
            android:orientation="vertical"
            android:gravity="center">

        <ImageView
                android:layout_width="64dp"
                android:layout_height="64dp"
                android:src="@drawable/ic_nav_music3d"
                android:alpha="0.6" />

        <TextView
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="16dp"
                android:text="@string/music3d_coming_soon"
                android:textColor="#A9ABAD"
                android:textSize="16sp" />
    </LinearLayout>
</FrameLayout>
EOF

echo "== Adicionando strings novas =="
if ! grep -q "nav_tab_gallery3d" "$STRINGS"; then
  sed -i 's#<string name="no_permission_message">.*</string>#&\n    <string name="nav_tab_gallery3d">Galeria3D</string>\n    <string name="nav_tab_music3d">Music3D</string>\n    <string name="music3d_coming_soon">Em construcao</string>#' "$STRINGS"
fi
grep -n "nav_tab_gallery3d\|nav_tab_music3d\|music3d_coming_soon" "$STRINGS"

echo "== Incluindo barra e placeholder no main.xml =="
python3 - << 'PYEOF'
path = "app/src/main/res/layout/main.xml"
with open(path) as f:
    content = f.read()

old = "</RelativeLayout>"
new = '''    <include layout="@layout/music3d_placeholder"/>
    <include layout="@layout/bottom_nav_bar"/>
</RelativeLayout>'''

if "bottom_nav_bar" not in content:
    assert content.count(old) == 1
    content = content.replace(old, new)
    with open(path, "w") as f:
        f.write(content)
    print("main.xml atualizado.")
else:
    print("main.xml ja tinha a barra, pulando.")
PYEOF

echo "== Restaurando GalleryActivity.java com a barra inferior integrada =="
base64 -d > "$JAVA_FILE" << 'B64_EOF'
LyoKICogQ29weXJpZ2h0IChDKSAyMDA5IFRoZSBBbmRyb2lkIE9wZW4gU291cmNlIFByb2plY3QKICoKICogTGljZW5zZWQgdW5kZXIgdGhlIEFwYWNoZSBMaWNlbnNlLCBWZXJzaW9uIDIuMCAodGhlICJMaWNlbnNlIik7CiAqIHlvdSBtYXkgbm90IHVzZSB0aGlzIGZpbGUgZXhjZXB0IGluIGNvbXBsaWFuY2Ugd2l0aCB0aGUgTGljZW5zZS4KICogWW91IG1heSBvYnRhaW4gYSBjb3B5IG9mIHRoZSBMaWNlbnNlIGF0CiAqCiAqICAgICAgaHR0cDovL3d3dy5hcGFjaGUub3JnL2xpY2Vuc2VzL0xJQ0VOU0UtMi4wCiAqCiAqIFVubGVzcyByZXF1aXJlZCBieSBhcHBsaWNhYmxlIGxhdyBvciBhZ3JlZWQgdG8gaW4gd3JpdGluZywgc29mdHdhcmUKICogZGlzdHJpYnV0ZWQgdW5kZXIgdGhlIExpY2Vuc2UgaXMgZGlzdHJpYnV0ZWQgb24gYW4gIkFTIElTIiBCQVNJUywKICogV0lUSE9VVCBXQVJSQU5USUVTIE9SIENPTkRJVElPTlMgT0YgQU5ZIEtJTkQsIGVpdGhlciBleHByZXNzIG9yIGltcGxpZWQuCiAqIFNlZSB0aGUgTGljZW5zZSBmb3IgdGhlIHNwZWNpZmljIGxhbmd1YWdlIGdvdmVybmluZyBwZXJtaXNzaW9ucyBhbmQKICogbGltaXRhdGlvbnMgdW5kZXIgdGhlIExpY2Vuc2UuCiAqLwoKcGFja2FnZSBjb20uYW5kcm9pZC5nYWxsZXJ5M2QuYXBwOwoKaW1wb3J0IGFuZHJvaWQuTWFuaWZlc3Q7CmltcG9ydCBhbmRyb2lkLmFwcC5EaWFsb2c7CmltcG9ydCBhbmRyb2lkLmNvbnRlbnQuQ29udGVudFJlc29sdmVyOwppbXBvcnQgYW5kcm9pZC5jb250ZW50LkRpYWxvZ0ludGVyZmFjZTsKaW1wb3J0IGFuZHJvaWQuY29udGVudC5EaWFsb2dJbnRlcmZhY2UuT25DYW5jZWxMaXN0ZW5lcjsKaW1wb3J0IGFuZHJvaWQuY29udGVudC5JbnRlbnQ7CmltcG9ydCBhbmRyb2lkLmNvbnRlbnQucG0uUGFja2FnZU1hbmFnZXI7CmltcG9ydCBhbmRyb2lkLm5ldC5Vcmk7CmltcG9ydCBhbmRyb2lkLm9zLkJ1aWxkOwppbXBvcnQgYW5kcm9pZC5vcy5CdW5kbGU7CmltcG9ydCBhbmRyb2lkLnZpZXcuSW5wdXREZXZpY2U7CmltcG9ydCBhbmRyb2lkLnZpZXcuTW90aW9uRXZlbnQ7CmltcG9ydCBhbmRyb2lkLnZpZXcuVmlldzsKaW1wb3J0IGFuZHJvaWQudmlldy5XaW5kb3c7CmltcG9ydCBhbmRyb2lkLnZpZXcuV2luZG93TWFuYWdlcjsKaW1wb3J0IGFuZHJvaWQud2lkZ2V0LlRvYXN0OwoKaW1wb3J0IGFuZHJvaWR4LmNvcmUuYXBwLkFjdGl2aXR5Q29tcGF0OwppbXBvcnQgYW5kcm9pZHguY29yZS5jb250ZW50LkNvbnRleHRDb21wYXQ7CgppbXBvcnQgY29tLmFuZHJvaWQuZ2FsbGVyeTNkLlI7CmltcG9ydCBjb20uYW5kcm9pZC5nYWxsZXJ5M2QuY29tbW9uLlV0aWxzOwppbXBvcnQgY29tLmFuZHJvaWQuZ2FsbGVyeTNkLmRhdGEuRGF0YU1hbmFnZXI7CmltcG9ydCBjb20uYW5kcm9pZC5nYWxsZXJ5M2QuZGF0YS5NZWRpYUl0ZW07CmltcG9ydCBjb20uYW5kcm9pZC5nYWxsZXJ5M2QuZGF0YS5NZWRpYVNldDsKaW1wb3J0IGNvbS5hbmRyb2lkLmdhbGxlcnkzZC5kYXRhLlBhdGg7CmltcG9ydCBjb20uYW5kcm9pZC5nYWxsZXJ5M2QucGljYXNhc291cmNlLlBpY2FzYVNvdXJjZTsKaW1wb3J0IGNvbS5hbmRyb2lkLmdhbGxlcnkzZC51dGlsLkdhbGxlcnlVdGlsczsKCnB1YmxpYyBmaW5hbCBjbGFzcyBHYWxsZXJ5QWN0aXZpdHkgZXh0ZW5kcyBBYnN0cmFjdEdhbGxlcnlBY3Rpdml0eSBpbXBsZW1lbnRzIE9uQ2FuY2VsTGlzdGVuZXIgewogICAgcHVibGljIHN0YXRpYyBmaW5hbCBTdHJpbmcgRVhUUkFfU0xJREVTSE9XID0gInNsaWRlc2hvdyI7CiAgICBwdWJsaWMgc3RhdGljIGZpbmFsIFN0cmluZyBFWFRSQV9EUkVBTSA9ICJkcmVhbSI7CiAgICBwdWJsaWMgc3RhdGljIGZpbmFsIFN0cmluZyBFWFRSQV9DUk9QID0gImNyb3AiOwoKICAgIHB1YmxpYyBzdGF0aWMgZmluYWwgU3RyaW5nIEFDVElPTl9SRVZJRVcgPSAiY29tLmFuZHJvaWQuY2FtZXJhLmFjdGlvbi5SRVZJRVciOwogICAgcHVibGljIHN0YXRpYyBmaW5hbCBTdHJpbmcgS0VZX0dFVF9DT05URU5UID0gImdldC1jb250ZW50IjsKICAgIHB1YmxpYyBzdGF0aWMgZmluYWwgU3RyaW5nIEtFWV9HRVRfQUxCVU0gPSAiZ2V0LWFsYnVtIjsKICAgIHB1YmxpYyBzdGF0aWMgZmluYWwgU3RyaW5nIEtFWV9UWVBFX0JJVFMgPSAidHlwZS1iaXRzIjsKICAgIHB1YmxpYyBzdGF0aWMgZmluYWwgU3RyaW5nIEtFWV9NRURJQV9UWVBFUyA9ICJtZWRpYVR5cGVzIjsKICAgIHB1YmxpYyBzdGF0aWMgZmluYWwgU3RyaW5nIEtFWV9ESVNNSVNTX0tFWUdVQVJEID0gImRpc21pc3Mta2V5Z3VhcmQiOwoKICAgIHByaXZhdGUgc3RhdGljIGZpbmFsIFN0cmluZyBUQUcgPSAiR2FsbGVyeUFjdGl2aXR5IjsKICAgIHByaXZhdGUgc3RhdGljIGZpbmFsIGludCBSRVFVRVNUX01FRElBX1BFUk1JU1NJT05TID0gMjAwMTsKCiAgICBwcml2YXRlIERpYWxvZyBtVmVyc2lvbkNoZWNrRGlhbG9nOwogICAgcHJpdmF0ZSBCdW5kbGUgbVBlbmRpbmdTYXZlZEluc3RhbmNlU3RhdGU7CiAgICBwcml2YXRlIGJvb2xlYW4gbUhhc1N0YXJ0ZWRTdGF0ZTsKCiAgICBwcml2YXRlIFZpZXcgbU5hdlRhYkdhbGxlcnkzZDsKICAgIHByaXZhdGUgVmlldyBtTmF2VGFiTXVzaWMzZDsKICAgIHByaXZhdGUgYW5kcm9pZC53aWRnZXQuVGV4dFZpZXcgbU5hdlRhYkdhbGxlcnkzZExhYmVsOwogICAgcHJpdmF0ZSBhbmRyb2lkLndpZGdldC5UZXh0VmlldyBtTmF2VGFiTXVzaWMzZExhYmVsOwogICAgcHJpdmF0ZSBWaWV3IG1NdXNpYzNkUGxhY2Vob2xkZXI7CiAgICBwcml2YXRlIFZpZXcgbUdsUm9vdFZpZXc7CiAgICBwcml2YXRlIFZpZXcgbUdsUm9vdENvdmVyOwoKICAgIHByaXZhdGUgc3RhdGljIFN0cmluZ1tdIGdldFJlcXVpcmVkTWVkaWFQZXJtaXNzaW9ucygpIHsKICAgICAgICBpZiAoQnVpbGQuVkVSU0lPTi5TREtfSU5UID49IDMzKSB7CiAgICAgICAgICAgIHJldHVybiBuZXcgU3RyaW5nW10gewogICAgICAgICAgICAgICAgICAgIE1hbmlmZXN0LnBlcm1pc3Npb24uUkVBRF9NRURJQV9JTUFHRVMsCiAgICAgICAgICAgICAgICAgICAgTWFuaWZlc3QucGVybWlzc2lvbi5SRUFEX01FRElBX1ZJREVPCiAgICAgICAgICAgIH07CiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgcmV0dXJuIG5ldyBTdHJpbmdbXSB7CiAgICAgICAgICAgICAgICAgICAgTWFuaWZlc3QucGVybWlzc2lvbi5SRUFEX0VYVEVSTkFMX1NUT1JBR0UsCiAgICAgICAgICAgICAgICAgICAgTWFuaWZlc3QucGVybWlzc2lvbi5XUklURV9FWFRFUk5BTF9TVE9SQUdFCiAgICAgICAgICAgIH07CiAgICAgICAgfQogICAgfQoKICAgIHByaXZhdGUgYm9vbGVhbiBoYXNNZWRpYVBlcm1pc3Npb25zKCkgewogICAgICAgIGZvciAoU3RyaW5nIHBlcm1pc3Npb24gOiBnZXRSZXF1aXJlZE1lZGlhUGVybWlzc2lvbnMoKSkgewogICAgICAgICAgICBpZiAoQ29udGV4dENvbXBhdC5jaGVja1NlbGZQZXJtaXNzaW9uKHRoaXMsIHBlcm1pc3Npb24pCiAgICAgICAgICAgICAgICAgICAgIT0gUGFja2FnZU1hbmFnZXIuUEVSTUlTU0lPTl9HUkFOVEVEKSB7CiAgICAgICAgICAgICAgICByZXR1cm4gZmFsc2U7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICAgICAgcmV0dXJuIHRydWU7CiAgICB9CgogICAgQE92ZXJyaWRlCiAgICBwcm90ZWN0ZWQgdm9pZCBvbkNyZWF0ZShCdW5kbGUgc2F2ZWRJbnN0YW5jZVN0YXRlKSB7CiAgICAgICAgc3VwZXIub25DcmVhdGUoc2F2ZWRJbnN0YW5jZVN0YXRlKTsKICAgICAgICByZXF1ZXN0V2luZG93RmVhdHVyZShXaW5kb3cuRkVBVFVSRV9BQ1RJT05fQkFSKTsKICAgICAgICByZXF1ZXN0V2luZG93RmVhdHVyZShXaW5kb3cuRkVBVFVSRV9BQ1RJT05fQkFSX09WRVJMQVkpOwoKICAgICAgICBpZiAoZ2V0SW50ZW50KCkuZ2V0Qm9vbGVhbkV4dHJhKEtFWV9ESVNNSVNTX0tFWUdVQVJELCBmYWxzZSkpIHsKICAgICAgICAgICAgZ2V0V2luZG93KCkuYWRkRmxhZ3MoCiAgICAgICAgICAgICAgICAgICAgV2luZG93TWFuYWdlci5MYXlvdXRQYXJhbXMuRkxBR19ESVNNSVNTX0tFWUdVQVJEKTsKICAgICAgICB9CgogICAgICAgIHNldENvbnRlbnRWaWV3KFIubGF5b3V0Lm1haW4pOwogICAgICAgIHNldHVwQm90dG9tTmF2KCk7CgogICAgICAgIGlmICghaGFzTWVkaWFQZXJtaXNzaW9ucygpKSB7CiAgICAgICAgICAgIG1QZW5kaW5nU2F2ZWRJbnN0YW5jZVN0YXRlID0gc2F2ZWRJbnN0YW5jZVN0YXRlOwogICAgICAgICAgICBBY3Rpdml0eUNvbXBhdC5yZXF1ZXN0UGVybWlzc2lvbnMoCiAgICAgICAgICAgICAgICAgICAgdGhpcywgZ2V0UmVxdWlyZWRNZWRpYVBlcm1pc3Npb25zKCksIFJFUVVFU1RfTUVESUFfUEVSTUlTU0lPTlMpOwogICAgICAgICAgICByZXR1cm47CiAgICAgICAgfQoKICAgICAgICBzdGFydE9yUmVzdG9yZVN0YXRlKHNhdmVkSW5zdGFuY2VTdGF0ZSk7CiAgICB9CgogICAgcHJpdmF0ZSB2b2lkIHNldHVwQm90dG9tTmF2KCkgewogICAgICAgIG1OYXZUYWJHYWxsZXJ5M2QgPSBmaW5kVmlld0J5SWQoUi5pZC5uYXZfdGFiX2dhbGxlcnkzZCk7CiAgICAgICAgbU5hdlRhYk11c2ljM2QgPSBmaW5kVmlld0J5SWQoUi5pZC5uYXZfdGFiX211c2ljM2QpOwogICAgICAgIG1OYXZUYWJHYWxsZXJ5M2RMYWJlbCA9IChhbmRyb2lkLndpZGdldC5UZXh0VmlldykgZmluZFZpZXdCeUlkKFIuaWQubmF2X3RhYl9nYWxsZXJ5M2RfbGFiZWwpOwogICAgICAgIG1OYXZUYWJNdXNpYzNkTGFiZWwgPSAoYW5kcm9pZC53aWRnZXQuVGV4dFZpZXcpIGZpbmRWaWV3QnlJZChSLmlkLm5hdl90YWJfbXVzaWMzZF9sYWJlbCk7CiAgICAgICAgbU11c2ljM2RQbGFjZWhvbGRlciA9IGZpbmRWaWV3QnlJZChSLmlkLm11c2ljM2RfcGxhY2Vob2xkZXJfcm9vdCk7CiAgICAgICAgbUdsUm9vdFZpZXcgPSBmaW5kVmlld0J5SWQoUi5pZC5nbF9yb290X3ZpZXcpOwogICAgICAgIG1HbFJvb3RDb3ZlciA9IGZpbmRWaWV3QnlJZChSLmlkLmdsX3Jvb3RfY292ZXIpOwoKICAgICAgICBpZiAobU5hdlRhYkdhbGxlcnkzZCAhPSBudWxsKSB7CiAgICAgICAgICAgIG1OYXZUYWJHYWxsZXJ5M2Quc2V0T25DbGlja0xpc3RlbmVyKG5ldyBWaWV3Lk9uQ2xpY2tMaXN0ZW5lcigpIHsKICAgICAgICAgICAgICAgIEBPdmVycmlkZQogICAgICAgICAgICAgICAgcHVibGljIHZvaWQgb25DbGljayhWaWV3IHYpIHsKICAgICAgICAgICAgICAgICAgICBzaG93R2FsbGVyeVRhYigpOwogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9KTsKICAgICAgICB9CiAgICAgICAgaWYgKG1OYXZUYWJNdXNpYzNkICE9IG51bGwpIHsKICAgICAgICAgICAgbU5hdlRhYk11c2ljM2Quc2V0T25DbGlja0xpc3RlbmVyKG5ldyBWaWV3Lk9uQ2xpY2tMaXN0ZW5lcigpIHsKICAgICAgICAgICAgICAgIEBPdmVycmlkZQogICAgICAgICAgICAgICAgcHVibGljIHZvaWQgb25DbGljayhWaWV3IHYpIHsKICAgICAgICAgICAgICAgICAgICBzaG93TXVzaWNUYWIoKTsKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgfSk7CiAgICAgICAgfQogICAgfQoKICAgIHByaXZhdGUgdm9pZCBzaG93R2FsbGVyeVRhYigpIHsKICAgICAgICBpZiAobU11c2ljM2RQbGFjZWhvbGRlciAhPSBudWxsKSBtTXVzaWMzZFBsYWNlaG9sZGVyLnNldFZpc2liaWxpdHkoVmlldy5HT05FKTsKICAgICAgICBpZiAobUdsUm9vdFZpZXcgIT0gbnVsbCkgbUdsUm9vdFZpZXcuc2V0VmlzaWJpbGl0eShWaWV3LlZJU0lCTEUpOwogICAgICAgIGlmIChtR2xSb290Q292ZXIgIT0gbnVsbCkgbUdsUm9vdENvdmVyLnNldFZpc2liaWxpdHkoVmlldy5WSVNJQkxFKTsKICAgICAgICBpZiAobU5hdlRhYkdhbGxlcnkzZCAhPSBudWxsKSB7CiAgICAgICAgICAgIG1OYXZUYWJHYWxsZXJ5M2Quc2V0QmFja2dyb3VuZFJlc291cmNlKFIuZHJhd2FibGUuYm90dG9tX25hdl9zZWxlY3RlZF9waWxsKTsKICAgICAgICB9CiAgICAgICAgaWYgKG1OYXZUYWJNdXNpYzNkICE9IG51bGwpIHsKICAgICAgICAgICAgbU5hdlRhYk11c2ljM2Quc2V0QmFja2dyb3VuZENvbG9yKGFuZHJvaWQuZ3JhcGhpY3MuQ29sb3IuVFJBTlNQQVJFTlQpOwogICAgICAgIH0KICAgICAgICBpZiAobU5hdlRhYkdhbGxlcnkzZExhYmVsICE9IG51bGwpIHsKICAgICAgICAgICAgbU5hdlRhYkdhbGxlcnkzZExhYmVsLnNldFRleHRDb2xvcihhbmRyb2lkLmdyYXBoaWNzLkNvbG9yLldISVRFKTsKICAgICAgICB9CiAgICAgICAgaWYgKG1OYXZUYWJNdXNpYzNkTGFiZWwgIT0gbnVsbCkgewogICAgICAgICAgICBtTmF2VGFiTXVzaWMzZExhYmVsLnNldFRleHRDb2xvcihhbmRyb2lkLmdyYXBoaWNzLkNvbG9yLnBhcnNlQ29sb3IoIiNBOUFCQUQiKSk7CiAgICAgICAgfQogICAgfQoKICAgIHByaXZhdGUgdm9pZCBzaG93TXVzaWNUYWIoKSB7CiAgICAgICAgaWYgKG1NdXNpYzNkUGxhY2Vob2xkZXIgIT0gbnVsbCkgbU11c2ljM2RQbGFjZWhvbGRlci5zZXRWaXNpYmlsaXR5KFZpZXcuVklTSUJMRSk7CiAgICAgICAgaWYgKG1HbFJvb3RWaWV3ICE9IG51bGwpIG1HbFJvb3RWaWV3LnNldFZpc2liaWxpdHkoVmlldy5HT05FKTsKICAgICAgICBpZiAobUdsUm9vdENvdmVyICE9IG51bGwpIG1HbFJvb3RDb3Zlci5zZXRWaXNpYmlsaXR5KFZpZXcuR09ORSk7CiAgICAgICAgaWYgKG1OYXZUYWJNdXNpYzNkICE9IG51bGwpIHsKICAgICAgICAgICAgbU5hdlRhYk11c2ljM2Quc2V0QmFja2dyb3VuZFJlc291cmNlKFIuZHJhd2FibGUuYm90dG9tX25hdl9zZWxlY3RlZF9waWxsKTsKICAgICAgICB9CiAgICAgICAgaWYgKG1OYXZUYWJHYWxsZXJ5M2QgIT0gbnVsbCkgewogICAgICAgICAgICBtTmF2VGFiR2FsbGVyeTNkLnNldEJhY2tncm91bmRDb2xvcihhbmRyb2lkLmdyYXBoaWNzLkNvbG9yLlRSQU5TUEFSRU5UKTsKICAgICAgICB9CiAgICAgICAgaWYgKG1OYXZUYWJNdXNpYzNkTGFiZWwgIT0gbnVsbCkgewogICAgICAgICAgICBtTmF2VGFiTXVzaWMzZExhYmVsLnNldFRleHRDb2xvcihhbmRyb2lkLmdyYXBoaWNzLkNvbG9yLldISVRFKTsKICAgICAgICB9CiAgICAgICAgaWYgKG1OYXZUYWJHYWxsZXJ5M2RMYWJlbCAhPSBudWxsKSB7CiAgICAgICAgICAgIG1OYXZUYWJHYWxsZXJ5M2RMYWJlbC5zZXRUZXh0Q29sb3IoYW5kcm9pZC5ncmFwaGljcy5Db2xvci5wYXJzZUNvbG9yKCIjQTlBQkFEIikpOwogICAgICAgIH0KICAgIH0KCiAgICBwcml2YXRlIHZvaWQgc3RhcnRPclJlc3RvcmVTdGF0ZShCdW5kbGUgc2F2ZWRJbnN0YW5jZVN0YXRlKSB7CiAgICAgICAgaWYgKHNhdmVkSW5zdGFuY2VTdGF0ZSAhPSBudWxsKSB7CiAgICAgICAgICAgIGdldFN0YXRlTWFuYWdlcigpLnJlc3RvcmVGcm9tU3RhdGUoc2F2ZWRJbnN0YW5jZVN0YXRlKTsKICAgICAgICB9IGVsc2UgewogICAgICAgICAgICBpbml0aWFsaXplQnlJbnRlbnQoKTsKICAgICAgICB9CiAgICAgICAgbUhhc1N0YXJ0ZWRTdGF0ZSA9IHRydWU7CiAgICB9CgogICAgQE92ZXJyaWRlCiAgICBwdWJsaWMgdm9pZCBvblJlcXVlc3RQZXJtaXNzaW9uc1Jlc3VsdChpbnQgcmVxdWVzdENvZGUsIFN0cmluZ1tdIHBlcm1pc3Npb25zLAogICAgICAgICAgICBpbnRbXSBncmFudFJlc3VsdHMpIHsKICAgICAgICBzdXBlci5vblJlcXVlc3RQZXJtaXNzaW9uc1Jlc3VsdChyZXF1ZXN0Q29kZSwgcGVybWlzc2lvbnMsIGdyYW50UmVzdWx0cyk7CiAgICAgICAgaWYgKHJlcXVlc3RDb2RlICE9IFJFUVVFU1RfTUVESUFfUEVSTUlTU0lPTlMpIHsKICAgICAgICAgICAgcmV0dXJuOwogICAgICAgIH0KICAgICAgICBpZiAoaGFzTWVkaWFQZXJtaXNzaW9ucygpKSB7CiAgICAgICAgICAgIHN0YXJ0T3JSZXN0b3JlU3RhdGUobVBlbmRpbmdTYXZlZEluc3RhbmNlU3RhdGUpOwogICAgICAgICAgICBtUGVuZGluZ1NhdmVkSW5zdGFuY2VTdGF0ZSA9IG51bGw7CiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgVG9hc3QubWFrZVRleHQodGhpcywgUi5zdHJpbmcubm9fcGVybWlzc2lvbl9tZXNzYWdlLCBUb2FzdC5MRU5HVEhfTE9ORykuc2hvdygpOwogICAgICAgICAgICBmaW5pc2goKTsKICAgICAgICB9CiAgICB9CgogICAgcHJpdmF0ZSB2b2lkIGluaXRpYWxpemVCeUludGVudCgpIHsKICAgICAgICBJbnRlbnQgaW50ZW50ID0gZ2V0SW50ZW50KCk7CiAgICAgICAgU3RyaW5nIGFjdGlvbiA9IGludGVudC5nZXRBY3Rpb24oKTsKCiAgICAgICAgaWYgKEludGVudC5BQ1RJT05fR0VUX0NPTlRFTlQuZXF1YWxzSWdub3JlQ2FzZShhY3Rpb24pKSB7CiAgICAgICAgICAgIHN0YXJ0R2V0Q29udGVudChpbnRlbnQpOwogICAgICAgIH0gZWxzZSBpZiAoSW50ZW50LkFDVElPTl9QSUNLLmVxdWFsc0lnbm9yZUNhc2UoYWN0aW9uKSkgewogICAgICAgICAgICAvLyBXZSBkbyBOT1QgcmVhbGx5IHN1cHBvcnQgdGhlIFBJQ0sgaW50ZW50LiBIYW5kbGUgaXQgYXMKICAgICAgICAgICAgLy8gdGhlIEdFVF9DT05URU5ULiBIb3dldmVyLCB3ZSBuZWVkIHRvIHRyYW5zbGF0ZSB0aGUgdHlwZQogICAgICAgICAgICAvLyBpbiB0aGUgaW50ZW50IGhlcmUuCiAgICAgICAgICAgIExvZy53KFRBRywgImFjdGlvbiBQSUNLIGlzIG5vdCBzdXBwb3J0ZWQiKTsKICAgICAgICAgICAgU3RyaW5nIHR5cGUgPSBVdGlscy5lbnN1cmVOb3ROdWxsKGludGVudC5nZXRUeXBlKCkpOwogICAgICAgICAgICBpZiAodHlwZS5zdGFydHNXaXRoKCJ2bmQuYW5kcm9pZC5jdXJzb3IuZGlyLyIpKSB7CiAgICAgICAgICAgICAgICBpZiAodHlwZS5lbmRzV2l0aCgiL2ltYWdlIikpIGludGVudC5zZXRUeXBlKCJpbWFnZS8qIik7CiAgICAgICAgICAgICAgICBpZiAodHlwZS5lbmRzV2l0aCgiL3ZpZGVvIikpIGludGVudC5zZXRUeXBlKCJ2aWRlby8qIik7CiAgICAgICAgICAgIH0KICAgICAgICAgICAgc3RhcnRHZXRDb250ZW50KGludGVudCk7CiAgICAgICAgfSBlbHNlIGlmIChJbnRlbnQuQUNUSU9OX1ZJRVcuZXF1YWxzSWdub3JlQ2FzZShhY3Rpb24pCiAgICAgICAgICAgICAgICB8fCBBQ1RJT05fUkVWSUVXLmVxdWFsc0lnbm9yZUNhc2UoYWN0aW9uKSl7CiAgICAgICAgICAgIHN0YXJ0Vmlld0FjdGlvbihpbnRlbnQpOwogICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgIHN0YXJ0RGVmYXVsdFBhZ2UoKTsKICAgICAgICB9CiAgICB9CgogICAgcHVibGljIHZvaWQgc3RhcnREZWZhdWx0UGFnZSgpIHsKICAgICAgICBQaWNhc2FTb3VyY2Uuc2hvd1NpZ25JblJlbWluZGVyKHRoaXMpOwogICAgICAgIEJ1bmRsZSBkYXRhID0gbmV3IEJ1bmRsZSgpOwogICAgICAgIGRhdGEucHV0U3RyaW5nKEFsYnVtU2V0UGFnZS5LRVlfTUVESUFfUEFUSCwKICAgICAgICAgICAgICAgIGdldERhdGFNYW5hZ2VyKCkuZ2V0VG9wU2V0UGF0aChEYXRhTWFuYWdlci5JTkNMVURFX0FMTCkpOwogICAgICAgIGdldFN0YXRlTWFuYWdlcigpLnN0YXJ0U3RhdGUoQWxidW1TZXRQYWdlLmNsYXNzLCBkYXRhKTsKICAgICAgICBtVmVyc2lvbkNoZWNrRGlhbG9nID0gUGljYXNhU291cmNlLmdldFZlcnNpb25DaGVja0RpYWxvZyh0aGlzKTsKICAgICAgICBpZiAobVZlcnNpb25DaGVja0RpYWxvZyAhPSBudWxsKSB7CiAgICAgICAgICAgIG1WZXJzaW9uQ2hlY2tEaWFsb2cuc2V0T25DYW5jZWxMaXN0ZW5lcih0aGlzKTsKICAgICAgICB9CiAgICB9CgogICAgcHJpdmF0ZSB2b2lkIHN0YXJ0R2V0Q29udGVudChJbnRlbnQgaW50ZW50KSB7CiAgICAgICAgQnVuZGxlIGRhdGEgPSBpbnRlbnQuZ2V0RXh0cmFzKCkgIT0gbnVsbAogICAgICAgICAgICAgICAgPyBuZXcgQnVuZGxlKGludGVudC5nZXRFeHRyYXMoKSkKICAgICAgICAgICAgICAgIDogbmV3IEJ1bmRsZSgpOwogICAgICAgIGRhdGEucHV0Qm9vbGVhbihLRVlfR0VUX0NPTlRFTlQsIHRydWUpOwogICAgICAgIGludCB0eXBlQml0cyA9IEdhbGxlcnlVdGlscy5kZXRlcm1pbmVUeXBlQml0cyh0aGlzLCBpbnRlbnQpOwogICAgICAgIGRhdGEucHV0SW50KEtFWV9UWVBFX0JJVFMsIHR5cGVCaXRzKTsKICAgICAgICBkYXRhLnB1dFN0cmluZyhBbGJ1bVNldFBhZ2UuS0VZX01FRElBX1BBVEgsCiAgICAgICAgICAgICAgICBnZXREYXRhTWFuYWdlcigpLmdldFRvcFNldFBhdGgodHlwZUJpdHMpKTsKICAgICAgICBnZXRTdGF0ZU1hbmFnZXIoKS5zdGFydFN0YXRlKEFsYnVtU2V0UGFnZS5jbGFzcywgZGF0YSk7CiAgICB9CgogICAgcHJpdmF0ZSBTdHJpbmcgZ2V0Q29udGVudFR5cGUoSW50ZW50IGludGVudCkgewogICAgICAgIFN0cmluZyB0eXBlID0gaW50ZW50LmdldFR5cGUoKTsKICAgICAgICBpZiAodHlwZSAhPSBudWxsKSB7CiAgICAgICAgICAgIHJldHVybiBHYWxsZXJ5VXRpbHMuTUlNRV9UWVBFX1BBTk9SQU1BMzYwLmVxdWFscyh0eXBlKQogICAgICAgICAgICAgICAgPyBNZWRpYUl0ZW0uTUlNRV9UWVBFX0pQRUcgOiB0eXBlOwogICAgICAgIH0KCiAgICAgICAgVXJpIHVyaSA9IGludGVudC5nZXREYXRhKCk7CiAgICAgICAgdHJ5IHsKICAgICAgICAgICAgcmV0dXJuIGdldENvbnRlbnRSZXNvbHZlcigpLmdldFR5cGUodXJpKTsKICAgICAgICB9IGNhdGNoIChUaHJvd2FibGUgdCkgewogICAgICAgICAgICBMb2cudyhUQUcsICJnZXQgdHlwZSBmYWlsIiwgdCk7CiAgICAgICAgICAgIHJldHVybiBudWxsOwogICAgICAgIH0KICAgIH0KCiAgICBwcml2YXRlIHZvaWQgc3RhcnRWaWV3QWN0aW9uKEludGVudCBpbnRlbnQpIHsKICAgICAgICBCb29sZWFuIHNsaWRlc2hvdyA9IGludGVudC5nZXRCb29sZWFuRXh0cmEoRVhUUkFfU0xJREVTSE9XLCBmYWxzZSk7CiAgICAgICAgaWYgKHNsaWRlc2hvdykgewogICAgICAgICAgICBnZXRBY3Rpb25CYXIoKS5oaWRlKCk7CiAgICAgICAgICAgIERhdGFNYW5hZ2VyIG1hbmFnZXIgPSBnZXREYXRhTWFuYWdlcigpOwogICAgICAgICAgICBQYXRoIHBhdGggPSBtYW5hZ2VyLmZpbmRQYXRoQnlVcmkoaW50ZW50LmdldERhdGEoKSwgaW50ZW50LmdldFR5cGUoKSk7CiAgICAgICAgICAgIGlmIChwYXRoID09IG51bGwgfHwgbWFuYWdlci5nZXRNZWRpYU9iamVjdChwYXRoKQogICAgICAgICAgICAgICAgICAgIGluc3RhbmNlb2YgTWVkaWFJdGVtKSB7CiAgICAgICAgICAgICAgICBwYXRoID0gUGF0aC5mcm9tU3RyaW5nKAogICAgICAgICAgICAgICAgICAgICAgICBtYW5hZ2VyLmdldFRvcFNldFBhdGgoRGF0YU1hbmFnZXIuSU5DTFVERV9JTUFHRSkpOwogICAgICAgICAgICB9CiAgICAgICAgICAgIEJ1bmRsZSBkYXRhID0gbmV3IEJ1bmRsZSgpOwogICAgICAgICAgICBkYXRhLnB1dFN0cmluZyhTbGlkZXNob3dQYWdlLktFWV9TRVRfUEFUSCwgcGF0aC50b1N0cmluZygpKTsKICAgICAgICAgICAgZGF0YS5wdXRCb29sZWFuKFNsaWRlc2hvd1BhZ2UuS0VZX1JBTkRPTV9PUkRFUiwgdHJ1ZSk7CiAgICAgICAgICAgIGRhdGEucHV0Qm9vbGVhbihTbGlkZXNob3dQYWdlLktFWV9SRVBFQVQsIHRydWUpOwogICAgICAgICAgICBpZiAoaW50ZW50LmdldEJvb2xlYW5FeHRyYShFWFRSQV9EUkVBTSwgZmFsc2UpKSB7CiAgICAgICAgICAgICAgICBkYXRhLnB1dEJvb2xlYW4oU2xpZGVzaG93UGFnZS5LRVlfRFJFQU0sIHRydWUpOwogICAgICAgICAgICB9CiAgICAgICAgICAgIGdldFN0YXRlTWFuYWdlcigpLnN0YXJ0U3RhdGUoU2xpZGVzaG93UGFnZS5jbGFzcywgZGF0YSk7CiAgICAgICAgfSBlbHNlIHsKICAgICAgICAgICAgQnVuZGxlIGRhdGEgPSBuZXcgQnVuZGxlKCk7CiAgICAgICAgICAgIERhdGFNYW5hZ2VyIGRtID0gZ2V0RGF0YU1hbmFnZXIoKTsKICAgICAgICAgICAgVXJpIHVyaSA9IGludGVudC5nZXREYXRhKCk7CiAgICAgICAgICAgIFN0cmluZyBjb250ZW50VHlwZSA9IGdldENvbnRlbnRUeXBlKGludGVudCk7CiAgICAgICAgICAgIGlmIChjb250ZW50VHlwZSA9PSBudWxsKSB7CiAgICAgICAgICAgICAgICBUb2FzdC5tYWtlVGV4dCh0aGlzLAogICAgICAgICAgICAgICAgICAgICAgICBSLnN0cmluZy5ub19zdWNoX2l0ZW0sIFRvYXN0LkxFTkdUSF9MT05HKS5zaG93KCk7CiAgICAgICAgICAgICAgICBmaW5pc2goKTsKICAgICAgICAgICAgICAgIHJldHVybjsKICAgICAgICAgICAgfQogICAgICAgICAgICBpZiAodXJpID09IG51bGwpIHsKICAgICAgICAgICAgICAgIGludCB0eXBlQml0cyA9IEdhbGxlcnlVdGlscy5kZXRlcm1pbmVUeXBlQml0cyh0aGlzLCBpbnRlbnQpOwogICAgICAgICAgICAgICAgZGF0YS5wdXRJbnQoS0VZX1RZUEVfQklUUywgdHlwZUJpdHMpOwogICAgICAgICAgICAgICAgZGF0YS5wdXRTdHJpbmcoQWxidW1TZXRQYWdlLktFWV9NRURJQV9QQVRILAogICAgICAgICAgICAgICAgICAgICAgICBnZXREYXRhTWFuYWdlcigpLmdldFRvcFNldFBhdGgodHlwZUJpdHMpKTsKICAgICAgICAgICAgICAgIGdldFN0YXRlTWFuYWdlcigpLnN0YXJ0U3RhdGUoQWxidW1TZXRQYWdlLmNsYXNzLCBkYXRhKTsKICAgICAgICAgICAgfSBlbHNlIGlmIChjb250ZW50VHlwZS5zdGFydHNXaXRoKAogICAgICAgICAgICAgICAgICAgIENvbnRlbnRSZXNvbHZlci5DVVJTT1JfRElSX0JBU0VfVFlQRSkpIHsKICAgICAgICAgICAgICAgIGludCBtZWRpYVR5cGUgPSBpbnRlbnQuZ2V0SW50RXh0cmEoS0VZX01FRElBX1RZUEVTLCAwKTsKICAgICAgICAgICAgICAgIGlmIChtZWRpYVR5cGUgIT0gMCkgewogICAgICAgICAgICAgICAgICAgIHVyaSA9IHVyaS5idWlsZFVwb24oKS5hcHBlbmRRdWVyeVBhcmFtZXRlcigKICAgICAgICAgICAgICAgICAgICAgICAgICAgIEtFWV9NRURJQV9UWVBFUywgU3RyaW5nLnZhbHVlT2YobWVkaWFUeXBlKSkKICAgICAgICAgICAgICAgICAgICAgICAgICAgIC5idWlsZCgpOwogICAgICAgICAgICAgICAgfQogICAgICAgICAgICAgICAgUGF0aCBzZXRQYXRoID0gZG0uZmluZFBhdGhCeVVyaSh1cmksIG51bGwpOwogICAgICAgICAgICAgICAgTWVkaWFTZXQgbWVkaWFTZXQgPSBudWxsOwogICAgICAgICAgICAgICAgaWYgKHNldFBhdGggIT0gbnVsbCkgewogICAgICAgICAgICAgICAgICAgIG1lZGlhU2V0ID0gKE1lZGlhU2V0KSBkbS5nZXRNZWRpYU9iamVjdChzZXRQYXRoKTsKICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIGlmIChtZWRpYVNldCAhPSBudWxsKSB7CiAgICAgICAgICAgICAgICAgICAgaWYgKG1lZGlhU2V0LmlzTGVhZkFsYnVtKCkpIHsKICAgICAgICAgICAgICAgICAgICAgICAgZGF0YS5wdXRTdHJpbmcoQWxidW1QYWdlLktFWV9NRURJQV9QQVRILCBzZXRQYXRoLnRvU3RyaW5nKCkpOwogICAgICAgICAgICAgICAgICAgICAgICBkYXRhLnB1dFN0cmluZyhBbGJ1bVBhZ2UuS0VZX1BBUkVOVF9NRURJQV9QQVRILAogICAgICAgICAgICAgICAgICAgICAgICAgICAgICAgIGRtLmdldFRvcFNldFBhdGgoRGF0YU1hbmFnZXIuSU5DTFVERV9BTEwpKTsKICAgICAgICAgICAgICAgICAgICAgICAgZ2V0U3RhdGVNYW5hZ2VyKCkuc3RhcnRTdGF0ZShBbGJ1bVBhZ2UuY2xhc3MsIGRhdGEpOwogICAgICAgICAgICAgICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEucHV0U3RyaW5nKEFsYnVtU2V0UGFnZS5LRVlfTUVESUFfUEFUSCwgc2V0UGF0aC50b1N0cmluZygpKTsKICAgICAgICAgICAgICAgICAgICAgICAgZ2V0U3RhdGVNYW5hZ2VyKCkuc3RhcnRTdGF0ZShBbGJ1bVNldFBhZ2UuY2xhc3MsIGRhdGEpOwogICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIH0gZWxzZSB7CiAgICAgICAgICAgICAgICAgICAgc3RhcnREZWZhdWx0UGFnZSgpOwogICAgICAgICAgICAgICAgfQogICAgICAgICAgICB9IGVsc2UgewogICAgICAgICAgICAgICAgUGF0aCBpdGVtUGF0aCA9IGRtLmZpbmRQYXRoQnlVcmkodXJpLCBjb250ZW50VHlwZSk7CiAgICAgICAgICAgICAgICBQYXRoIGFsYnVtUGF0aCA9IGRtLmdldERlZmF1bHRTZXRPZihpdGVtUGF0aCk7CgogICAgICAgICAgICAgICAgZGF0YS5wdXRTdHJpbmcoUGhvdG9QYWdlLktFWV9NRURJQV9JVEVNX1BBVEgsIGl0ZW1QYXRoLnRvU3RyaW5nKCkpOwogICAgICAgICAgICAgICAgZGF0YS5wdXRCb29sZWFuKFBob3RvUGFnZS5LRVlfUkVBRE9OTFksIHRydWUpOwoKICAgICAgICAgICAgICAgIC8vIFRPRE86IE1ha2UgdGhlIHBhcmFtZXRlciAiU2luZ2xlSXRlbU9ubHkiIHB1YmxpYyBzbyBvdGhlcgogICAgICAgICAgICAgICAgLy8gICAgICAgYWN0aXZpdGllcyBjYW4gcmVmZXJlbmNlIGl0LgogICAgICAgICAgICAgICAgYm9vbGVhbiBzaW5nbGVJdGVtT25seSA9IChhbGJ1bVBhdGggPT0gbnVsbCkKICAgICAgICAgICAgICAgICAgICAgICAgfHwgaW50ZW50LmdldEJvb2xlYW5FeHRyYSgiU2luZ2xlSXRlbU9ubHkiLCBmYWxzZSk7CiAgICAgICAgICAgICAgICBpZiAoIXNpbmdsZUl0ZW1Pbmx5KSB7CiAgICAgICAgICAgICAgICAgICAgZGF0YS5wdXRTdHJpbmcoUGhvdG9QYWdlLktFWV9NRURJQV9TRVRfUEFUSCwgYWxidW1QYXRoLnRvU3RyaW5nKCkpOwogICAgICAgICAgICAgICAgICAgIC8vIHdoZW4gRkxBR19BQ1RJVklUWV9ORVdfVEFTSyBpcyBzZXQsIChlLmcuIHdoZW4gaW50ZW50IGlzIGZpcmVkCiAgICAgICAgICAgICAgICAgICAgLy8gZnJvbSBub3RpZmljYXRpb24pLCBiYWNrIGJ1dHRvbiBzaG91bGQgYmVoYXZlIHRoZSBzYW1lIGFzIHVwIGJ1dHRvbgogICAgICAgICAgICAgICAgICAgIC8vIHJhdGhlciB0aGFuIHRha2luZyB1c2VycyBiYWNrIHRvIHRoZSBob21lIHNjcmVlbgogICAgICAgICAgICAgICAgICAgIGlmIChpbnRlbnQuZ2V0Qm9vbGVhbkV4dHJhKFBob3RvUGFnZS5LRVlfVFJFQVRfQkFDS19BU19VUCwgZmFsc2UpCiAgICAgICAgICAgICAgICAgICAgICAgICAgICB8fCAoKGludGVudC5nZXRGbGFncygpICYgSW50ZW50LkZMQUdfQUNUSVZJVFlfTkVXX1RBU0spICE9IDApKSB7CiAgICAgICAgICAgICAgICAgICAgICAgIGRhdGEucHV0Qm9vbGVhbihQaG90b1BhZ2UuS0VZX1RSRUFUX0JBQ0tfQVNfVVAsIHRydWUpOwogICAgICAgICAgICAgICAgICAgIH0KICAgICAgICAgICAgICAgIH0KCiAgICAgICAgICAgICAgICBnZXRTdGF0ZU1hbmFnZXIoKS5zdGFydFN0YXRlKFNpbmdsZVBob3RvUGFnZS5jbGFzcywgZGF0YSk7CiAgICAgICAgICAgIH0KICAgICAgICB9CiAgICB9CgogICAgQE92ZXJyaWRlCiAgICBwcm90ZWN0ZWQgdm9pZCBvblJlc3VtZSgpIHsKICAgICAgICBpZiAobUhhc1N0YXJ0ZWRTdGF0ZSkgewogICAgICAgICAgICBVdGlscy5hc3NlcnRUcnVlKGdldFN0YXRlTWFuYWdlcigpLmdldFN0YXRlQ291bnQoKSA+IDApOwogICAgICAgIH0KICAgICAgICBzdXBlci5vblJlc3VtZSgpOwogICAgICAgIGlmIChtVmVyc2lvbkNoZWNrRGlhbG9nICE9IG51bGwpIHsKICAgICAgICAgICAgbVZlcnNpb25DaGVja0RpYWxvZy5zaG93KCk7CiAgICAgICAgfQogICAgfQoKICAgIEBPdmVycmlkZQogICAgcHJvdGVjdGVkIHZvaWQgb25QYXVzZSgpIHsKICAgICAgICBzdXBlci5vblBhdXNlKCk7CiAgICAgICAgaWYgKG1WZXJzaW9uQ2hlY2tEaWFsb2cgIT0gbnVsbCkgewogICAgICAgICAgICBtVmVyc2lvbkNoZWNrRGlhbG9nLmRpc21pc3MoKTsKICAgICAgICB9CiAgICB9CgogICAgQE92ZXJyaWRlCiAgICBwdWJsaWMgdm9pZCBvbkNhbmNlbChEaWFsb2dJbnRlcmZhY2UgZGlhbG9nKSB7CiAgICAgICAgaWYgKGRpYWxvZyA9PSBtVmVyc2lvbkNoZWNrRGlhbG9nKSB7CiAgICAgICAgICAgIG1WZXJzaW9uQ2hlY2tEaWFsb2cgPSBudWxsOwogICAgICAgIH0KICAgIH0KCiAgICBAT3ZlcnJpZGUKICAgIHB1YmxpYyBib29sZWFuIG9uR2VuZXJpY01vdGlvbkV2ZW50KE1vdGlvbkV2ZW50IGV2ZW50KSB7CiAgICAgICAgZmluYWwgYm9vbGVhbiBpc1RvdWNoUGFkID0gKGV2ZW50LmdldFNvdXJjZSgpCiAgICAgICAgICAgICAgICAmIElucHV0RGV2aWNlLlNPVVJDRV9DTEFTU19QT1NJVElPTikgIT0gMDsKICAgICAgICBpZiAoaXNUb3VjaFBhZCkgewogICAgICAgICAgICBmbG9hdCBtYXhYID0gZXZlbnQuZ2V0RGV2aWNlKCkuZ2V0TW90aW9uUmFuZ2UoTW90aW9uRXZlbnQuQVhJU19YKS5nZXRNYXgoKTsKICAgICAgICAgICAgZmxvYXQgbWF4WSA9IGV2ZW50LmdldERldmljZSgpLmdldE1vdGlvblJhbmdlKE1vdGlvbkV2ZW50LkFYSVNfWSkuZ2V0TWF4KCk7CiAgICAgICAgICAgIFZpZXcgZGVjb3IgPSBnZXRXaW5kb3coKS5nZXREZWNvclZpZXcoKTsKICAgICAgICAgICAgZmxvYXQgc2NhbGVYID0gZGVjb3IuZ2V0V2lkdGgoKSAvIG1heFg7CiAgICAgICAgICAgIGZsb2F0IHNjYWxlWSA9IGRlY29yLmdldEhlaWdodCgpIC8gbWF4WTsKICAgICAgICAgICAgZmxvYXQgeCA9IGV2ZW50LmdldFgoKSAqIHNjYWxlWDsKICAgICAgICAgICAgLy94ID0gZGVjb3IuZ2V0V2lkdGgoKSAtIHg7IC8vIGludmVydCB4CiAgICAgICAgICAgIGZsb2F0IHkgPSBldmVudC5nZXRZKCkgKiBzY2FsZVk7CiAgICAgICAgICAgIC8veSA9IGRlY29yLmdldEhlaWdodCgpIC0geTsgLy8gaW52ZXJ0IHkKICAgICAgICAgICAgTW90aW9uRXZlbnQgdG91Y2hFdmVudCA9IE1vdGlvbkV2ZW50Lm9idGFpbihldmVudC5nZXREb3duVGltZSgpLAogICAgICAgICAgICAgICAgICAgIGV2ZW50LmdldEV2ZW50VGltZSgpLCBldmVudC5nZXRBY3Rpb24oKSwgeCwgeSwgZXZlbnQuZ2V0TWV0YVN0YXRlKCkpOwogICAgICAgICAgICByZXR1cm4gZGlzcGF0Y2hUb3VjaEV2ZW50KHRvdWNoRXZlbnQpOwogICAgICAgIH0KICAgICAgICByZXR1cm4gc3VwZXIub25HZW5lcmljTW90aW9uRXZlbnQoZXZlbnQpOwogICAgfQp9Cg==
B64_EOF

echo "== Fim: bottom nav instalado =="
